;;; ox-epub3-latex.el --- LaTeX to SVG via dvisvgm -*- lexical-binding: t; -*-

;; Copyright (C) 2026 Nicola Ferru Aka NFVblog

;; This file is not part of GNU Emacs.

;;; Code:

(require 'ox-epub3-kernel)

;;; --- LaTeX / SVG (dvisvgm) ---

(defvar org-epub3--has-svg nil
  "Non-nil when current export contains inline SVG content.")

(defun org-epub3--dvisvgm-available-p ()
  "Return non-nil if dvisvgm and latex are available in PATH."
  (and (executable-find "dvisvgm") (executable-find "latex")))

(defun org-epub3--latex-to-mathml (latex-str &optional displayp)
  "Convert LATEX-STR to MathML using pandoc.
When DISPLAYP is non-nil, use display-math mode.
Returns MathML string or nil on failure."
  (let ((pandoc (executable-find "pandoc")))
    (when pandoc
      (with-temp-buffer
        (insert latex-str)
        (let ((exit-code (call-process-region
                          (point-min) (point-max)
                          pandoc nil t nil
                          "-f" "latex" "-t" "mathml")))
          (when (and (zerop exit-code) (> (buffer-size) 0))
            (let ((mathml (string-trim (buffer-string))))
              (if displayp
                  (concat "<div class=\"equation\">\n" mathml "\n</div>")
                (concat "<span class=\"math\">" mathml "</span>")))))))))

(defun org-epub3--latex-to-svg (latex-str &optional displayp)
  "Convert LATEX-STR to an SVG string using dvisvgm.
When DISPLAYP is non-nil, use display-math mode.
Returns SVG string or nil on failure."
  (when (org-epub3--dvisvgm-available-p)
    (let ((tex-file (make-temp-file "ox-epub3-math-" nil ".tex"))
          (svg-file nil))
      (unwind-protect
          (progn
            (with-temp-file tex-file
              (insert
               "\\documentclass{article}\n"
               "\\usepackage{amsmath,amssymb}\n"
               "\\usepackage[active,tightpage]{preview}\n"
               "\\begin{document}\n"
               "\\begin{preview}\n"
               (if displayp
                   (concat "\\[" latex-str "\\]")
                 (concat "$" latex-str "$"))
               "\n\\end{preview}\n"
               "\\end{document}\n"))
            (call-process "latex" nil nil nil
                          "-interaction=nonstopmode"
                          "-output-directory"
                          (file-name-directory tex-file)
                          tex-file)
            (let* ((base (file-name-sans-extension tex-file))
                   (dvi-file (concat base ".dvi")))
              (when (file-exists-p dvi-file)
                (setq svg-file (concat base ".svg"))
                (call-process "dvisvgm" nil nil nil
                              "--no-fonts"
                              "--exact-bbox"
                              "-o" svg-file
                              dvi-file)
                (when (and svg-file (file-exists-p svg-file))
                  (with-temp-buffer
                    (insert-file-contents svg-file)
                    (let ((svg (buffer-string))
                          (prefix (format "m%d-" (abs (sxhash latex-str)))))
                      ;; Strip XML declaration for inline embedding in XHTML
                      (when (string-match "\\`<\\?xml[^?]*\\?>\n?" svg)
                        (setq svg (replace-match "" t t svg)))
                      ;; Strip dvisvgm comment
                      (when (string-match "<!-- This file was generated by dvisvgm[^>]* -->\n?" svg)
                        (setq svg (replace-match "" t t svg)))
                      ;; Ensure SVG has proper xmlns for XHTML (double quotes)
                      (when (string-match "<svg " svg)
                        (setq svg
                              (replace-regexp-in-string
                               "xmlns='http://www.w3.org/2000/svg'"
                               "xmlns=\"http://www.w3.org/2000/svg\""
                               svg nil t))
                        (setq svg
                              (replace-regexp-in-string
                               "xmlns:xlink='http://www.w3.org/1999/xlink'"
                               "xmlns:xlink=\"http://www.w3.org/1999/xlink\""
                               svg nil t)))
                      ;; Make IDs unique to avoid conflicts in same document
                      ;; Prefix all id= and xlink:href= references
                      (let ((pfx prefix))
                        (setq svg (replace-regexp-in-string
                                    "id='\\([^']*\\)'"
                                    (lambda (m)
                                      (concat "id='" pfx (match-string 1 m) "'"))
                                    svg nil t))
                        (setq svg (replace-regexp-in-string
                                    "xlink:href='#\\([^']*\\)'"
                                    (lambda (m)
                                      (concat "xlink:href='#" pfx (match-string 1 m) "'"))
                                    svg nil t)))
                      svg))))))
        ;; Cleanup temp files
        (when (file-exists-p tex-file)
          (delete-file tex-file))
        (let ((base (file-name-sans-extension tex-file)))
          (dolist (ext '(".log" ".aux" ".dvi" ".pdf" ".svg"))
            (when (file-exists-p (concat base ext))
              (delete-file (concat base ext)))))))))

(defun org-epub3--latex-fragment (latex-fragment _contents _info)
  "Transcode LATEX-FRAGMENT to inline SVG via dvisvgm, or MathML fallback.
CONTENTS is nil.  INFO is the export plist."
  (let* ((latex-str (org-element-property :value latex-fragment))
         (svg (when (org-epub3--dvisvgm-available-p)
                (org-epub3--latex-to-svg latex-str nil))))
    (cond
     (svg
      (setq org-epub3--has-svg t)
      (concat "<span class=\"math\">"
              svg
              "</span>"))
     ((org-epub3--latex-to-mathml latex-str nil))
     (t
      (concat "<code class=\"latex-fragment\">"
              (org-epub3--esc latex-str)
              "</code>")))))

(defun org-epub3--latex-environment (latex-environment _contents _info)
  "Transcode LATEX-ENVIRONMENT to SVG via dvisvgm, or MathML fallback.
CONTENTS is nil.  INFO is the export plist."
  (let* ((latex-str (org-remove-indentation
                     (org-element-property :value latex-environment)))
         (svg (when (org-epub3--dvisvgm-available-p)
                (org-epub3--latex-to-svg latex-str t))))
    (cond
     (svg
      (setq org-epub3--has-svg t)
      (concat "<div class=\"equation\">\n"
              svg
              "\n</div>"))
     ((org-epub3--latex-to-mathml latex-str t))
     (t
      (concat "<pre class=\"latex-environment\">"
              (org-epub3--esc latex-str)
              "</pre>")))))

(provide 'ox-epub3-latex)
;;; ox-epub3-latex.el ends here
